package bean;
// Generated 16/12/2024 11:49:20 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="db_kender_gomes"
)
public class Pedidos  implements java.io.Serializable {


     private int idPedidos;

    public Pedidos() {
    }

	
    public Pedidos(int idPedidos) {
        this.idPedidos = idPedidos;
    }
    public Pedidos(int idPedidos, String pedidoscol) {
       this.idPedidos = idPedidos;
    }
   
     @Id 

    
    @Column(name="id_pedidos", unique=true, nullable=false)
    public int getIdPedidos() {
        return this.idPedidos;
    }
    
    public void setIdPedidos(int idPedidos) {
        this.idPedidos = idPedidos;
    }



}


