package bean;
// Generated 16/12/2024 11:49:20 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProdutosKhp generated by hbm2java
 */
@Entity
@Table(name="produtos_khp"
    ,catalog="db_kender_gomes"
)
public class ProdutosKhp  implements java.io.Serializable {


     private int idProdutosKhp;
     private String materialKhp;
     private String descricaoKhp;
     private Double precoKhp;
     private String tamanhoKhp;
     private String corKhp;
     private String marcaKhp;

    public ProdutosKhp() {
    }

    public ProdutosKhp(String materialKhp, String descricaoKhp, Double precoKhp, String tamanhoKhp, String corKhp, String marcaKhp, Set vendasProdutosKhps) {
       this.materialKhp = materialKhp;
       this.descricaoKhp = descricaoKhp;
       this.precoKhp = precoKhp;
       this.tamanhoKhp = tamanhoKhp;
       this.corKhp = corKhp;
       this.marcaKhp = marcaKhp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_produtos_khp", unique=true, nullable=false)
    public int getIdProdutosKhp() {
        return this.idProdutosKhp;
    }
    
    public void setIdProdutosKhp(int idProdutosKhp) {
        this.idProdutosKhp = idProdutosKhp;
    }

    
    @Column(name="material_khp", length=50)
    public String getMaterialKhp() {
        return this.materialKhp;
    }
    
    public void setMaterialKhp(String materialKhp) {
        this.materialKhp = materialKhp;
    }

    
    @Column(name="descricao_khp", length=65535)
    public String getDescricaoKhp() {
        return this.descricaoKhp;
    }
    
    public void setDescricaoKhp(String descricaoKhp) {
        this.descricaoKhp = descricaoKhp;
    }

    
    @Column(name="preco_khp", precision=10)
    public Double getPrecoKhp() {
        return this.precoKhp;
    }
    
    public void setPrecoKhp(Double precoKhp) {
        this.precoKhp = precoKhp;
    }

    
    @Column(name="tamanho_khp", length=10)
    public String getTamanhoKhp() {
        return this.tamanhoKhp;
    }
    
    public void setTamanhoKhp(String tamanhoKhp) {
        this.tamanhoKhp = tamanhoKhp;
    }

    
    @Column(name="cor_khp", length=50)
    public String getCorKhp() {
        return this.corKhp;
    }
    
    public void setCorKhp(String corKhp) {
        this.corKhp = corKhp;
    }

    
    @Column(name="marca_khp", length=50)
    public String getMarcaKhp() {
        return this.marcaKhp;
    }
    
    public void setMarcaKhp(String marcaKhp) {
        this.marcaKhp = marcaKhp;
    }

}


