package bean;
// Generated 16/12/2024 11:49:20 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosKhp generated by hbm2java
 */
@Entity
@Table(name="usuarios_khp"
    ,catalog="db_kender_gomes"
)
public class UsuariosKhp  implements java.io.Serializable {


     private int idUsuariosKhp;
     private String nomeKhp;
     private String apelidoKhp;
     private String cpfKhp;
     private Date dataNascimentoKhp;
     private String senhaKhp;
     private Integer nivelKhp;
     private String ativoKhp;

    public UsuariosKhp() {
    }

	
    public UsuariosKhp(int idUsuariosKhp) {
        this.idUsuariosKhp = idUsuariosKhp;
    }
    public UsuariosKhp(int idUsuariosKhp, String nomeKhp, String apelidoKhp, String cpfKhp, Date dataNascimentoKhp, String senhaKhp, Integer nivelKhp, String ativoKhp) {
       this.idUsuariosKhp = idUsuariosKhp;
       this.nomeKhp = nomeKhp;
       this.apelidoKhp = apelidoKhp;
       this.cpfKhp = cpfKhp;
       this.dataNascimentoKhp = dataNascimentoKhp;
       this.senhaKhp = senhaKhp;
       this.nivelKhp = nivelKhp;
       this.ativoKhp = ativoKhp;
    }
   
     @Id 

    
    @Column(name="id_usuarios_khp", unique=true, nullable=false)
    public int getIdUsuariosKhp() {
        return this.idUsuariosKhp;
    }
    
    public void setIdUsuariosKhp(int idUsuariosKhp) {
        this.idUsuariosKhp = idUsuariosKhp;
    }

    
    @Column(name="nome_khp", length=50)
    public String getNomeKhp() {
        return this.nomeKhp;
    }
    
    public void setNomeKhp(String nomeKhp) {
        this.nomeKhp = nomeKhp;
    }

    
    @Column(name="apelido_khp", length=15)
    public String getApelidoKhp() {
        return this.apelidoKhp;
    }
    
    public void setApelidoKhp(String apelidoKhp) {
        this.apelidoKhp = apelidoKhp;
    }

    
    @Column(name="cpf_khp", length=14)
    public String getCpfKhp() {
        return this.cpfKhp;
    }
    
    public void setCpfKhp(String cpfKhp) {
        this.cpfKhp = cpfKhp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_khp", length=10)
    public Date getDataNascimentoKhp() {
        return this.dataNascimentoKhp;
    }
    
    public void setDataNascimentoKhp(Date dataNascimentoKhp) {
        this.dataNascimentoKhp = dataNascimentoKhp;
    }

    
    @Column(name="senha_khp", length=15)
    public String getSenhaKhp() {
        return this.senhaKhp;
    }
    
    public void setSenhaKhp(String senhaKhp) {
        this.senhaKhp = senhaKhp;
    }

    
    @Column(name="nivel_khp")
    public Integer getNivelKhp() {
        return this.nivelKhp;
    }
    
    public void setNivelKhp(Integer nivelKhp) {
        this.nivelKhp = nivelKhp;
    }

    
    @Column(name="ativo_khp", length=1)
    public String getAtivoKhp() {
        return this.ativoKhp;
    }
    
    public void setAtivoKhp(String ativoKhp) {
        this.ativoKhp = ativoKhp;
    }




}


